services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: resolute 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db

  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3000  # Start FastAPI
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/resolute
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - app
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/resolute
      REDIS_URL: redis://redis:6379/0
    command: celery -A main.celery_app worker --pool=solo --loglevel=info

volumes:
  postgres_data:
