name : Webscraping

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Virtual Env
        run: pip install virtualenv
      - name : Install Dependencies
        run : python -m venv env && source env/bin/activate && pip install -r requirements.txt

       